### PR TITLE
Explicit memory management (closes #276)

### LINKED ISSUE #276: Remove ref_ptr
With https://github.com/hpicgs/globjects/pull/275 the discussion comes up why we provide an own implementation of a smart pointer (```ref_ptr```), if the STL provides ```unique_ptr```, ```shared_ptr``` and ```weak_ptr```.

Typically, objects in globjects are strictly related to an OpenGL object, so there is a 1 to 1 correspondence and with a creation or destruction of a globjects objects there should follow the same for the OpenGL object.
As objects (e.g., a shader) can be used in different ways by multiple other objects (e.g., multiple programs sharing the same fragment shader), it may not be clear when an globjects object isn't used anymore and the corresponding OpenGL resource can be freed.
The problem gets even more complicated when we want to allow other OpenGL libraries to use OpenGL objects allocated by globjects (and the other way around).
Therefore, our first solution was to introduce a shared ownership architecture, as it can be established using ```shared_ptr``` or ```ref_ptr```.
```ref_ptr``` has the main advantage over ```shared_ptr``` that the reference counting is on the object itself, resulting in smaller and clearer function signatures.
The disadvantage is the required own implementation, as a ```ref_ptr``` is not shipped with the STL (by now?).

While analyzing past and current rendering systems (e.g., research prototypes, game engines, cg demos) it becomes apparent that there is not only a common phase for creating OpenGL objects but also a dedicated phase were OpenGL objects are freed.
As I assume that every programmer using OpenGL knows (or at least should know) when to allocate and free OpenGL memory, it feels prematurely optimized that we introduced a shared memory ownership and management in the first place.

I suggest we switch back to simple, straight-forward memory management using ```unique_ptr``` (indicating memory ownership) and plain pointers (indicating no memory ownership), as seen in http://stackoverflow.com/questions/8338570/c11-replace-all-non-owning-raw-pointers-with-stdshared-ptr#answer-8376611.

### PR DESCRIPTION
**Pull request by scheibel**
Current solution to remove ```ref_ptr``` in globjects.

Open issues
* test bindless textures
* adapt to osg example
* restructure ShaderIncludeProcessor to get rid of memory leak
* restructure global replacements to get rid of memory leak
* restructure NamedStrings to get rid of memory leak
* rethink interface to get program binary from program (currently a memory leak)

What is your impression on the changes and implications on depending libraries / programs?

### CODE REVIEW

**Comment by scheibel** [comment]
E.g. during the refactoring of IncludeProcessor the functionality can be moved to gloperate.

**Comment by j-o** [comment]
This does not compile on MSVC because `unique_ptr`s can't be used with forward declared types (produces  `error C2338: can't delete an incomplete type`).

While allowing explicit memory management might generally be a good idea, I think in the current state the price in terms of convenience loss is much too high. My primary concern here is the whole StringSource/Shader/Progam/Uniform architecture that now easily requires managing 10 or more pointers (e.g. 3 Shaders, 3 StringSources, 1 Program, 2 Uniforms)  instead of a single one.

Further, I think the `IncludeProcessor` should remain here, as it directly emulates OpenGL functionality. The current `ShadingLanguageIncludeImplementation` architecture allows the transparent fallback, which would not  be possible with the `IncludeProcessor` living elsewhere.

**Comment by scheibel** [comment]
> This does not compile on MSVC because ```unique_ptr```s can't be used with forward declared types (produces ```error C2338: can't delete an incomplete type```).

Quite unfortunate, but this can be fixed.

> While allowing explicit memory management might generally be a good idea, I think in the current state the price in terms of convenience loss is much too high. My primary concern here is the whole StringSource/Shader/Progam/Uniform architecture that now easily requires managing 10 or more pointers (e.g. 3 Shaders, 3 StringSources, 1 Program, 2 Uniforms) instead of a single one.

The issue with Uniforms can be addressed using ```UniformGroup``` (in [gloperate](https://github.com/hpicgs/gloperate/blob/master/source/gloperate/include/gloperate/primitives/UniformGroup.h)) or ```UniformManager``` (probably integrated into gloperate).
The issue with the shaders and their sources (as well as the ```IncludeProcessor``` restructuring) can be fixed with declaring pointer ownership of shaders over their shader sources, but with the drawback of denied sharing of sources between shaders.
The same sharing argument can be applied between the sharing of shaders between programs (and uniforms and programs).

> Further, I think the ```IncludeProcessor``` should remain here, as it directly emulates OpenGL functionality. The current ```ShadingLanguageIncludeImplementation``` architecture allows the transparent fallback, which would not be possible with the ```IncludeProcessor``` living elsewhere.

This decision should be based on the granularity of object oriented wrapping intended by globjects. If we intend to provide just a simple object-oriented wrapper around OpenGL, such a feature wouldn't fit in there. gloperate is designed to provide more graphics-rendering-engine-like functionalities, so emulating such complex feature would fit there just fine.
Currently, globjects supports several convenience features that are not part of a strict OpenGL object oriented interface but a rendering engine.
Either we should reconsider the current abstraction in globjects or try live with the consequences.

**Comment by scheibel** [comment]
Jenkins, retest this please.

**Pull request closed without merging**
